version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Add date meta data
          command: bash meta-date.sh
      - run:
          name: Install test dependencies
          command: pip3 install BeautifulSoup4
      - run:
          name: Test carousel
          command: python3 validate-carousels.py
  deploy-staging:
    docker:
      - image: govau/cf-cli
    steps:
      - checkout
      - run:
          name: Add date meta data
          command: bash meta-date.sh
      - run:
          name: Deploying to cloud.gov.au
          command: |
            cf login -a $CF_API_STAGING -o $CF_ORG -s $CF_SPACE -u $CF_USERNAME -p $CF_PASSWORD_STAGING
            cp config/stag_manifest.yml site/manifest.yml
            cd site
            cf zero-downtime-push original-ausgov -f manifest.yml
      - run:
          name: Purging Fastly cache
          command: bash purge-cache.sh $FASTLY_URL_STAGING
  deploy-prod:
    docker:
      - image: govau/cf-cli
    steps:
      - checkout
      - run:
          name: Add date meta data
          command: bash meta-date.sh
      - run:
          name: Deploying to cloud.gov.au
          command: |
            cf login -a $CF_API_PROD -o $CF_ORG -s $CF_SPACE -u $CF_USERNAME -p $CF_PASSWORD_PROD
            cp config/prod_manifest.yml site/manifest.yml
            cd site
            cf zero-downtime-push original-ausgov -f manifest.yml
      - run:
          name: Purging Fastly cache
          command: bash purge-cache.sh $FASTLY_URL_PROD
workflows:
  version: 2
  deploy:
    jobs:
      - test
      - deploy-staging:
          filters:
            branches:
              only:
                - develop
      - deploy-prod:
          filters:
            branches:
              only:
                - master
