version: 2
jobs:
  deploy-covid:
    docker:
      - image: govau/cf-cli
    steps:
      - checkout
      - run:
          name: Deploying to cloud.gov.au
          command: |
            cf login -a $CF_API_STAGING -o $CF_ORG -s $CF_SPACE -u $CF_USERNAME -p $CF_PASSWORD_STAGING
            cp config/covid_manifest.yml site/manifest.yml
            cp site/covid_nginx.conf site/nginx.conf
            cd site
            cf zero-downtime-push covid-ausgov -f manifest.yml
  deploy-staging:
    docker:
      - image: govau/cf-cli
    steps:
      - checkout
      - run:
          name: Deploying to cloud.gov.au
          command: |
            cf login -a $CF_API_STAGING -o $CF_ORG -s $CF_SPACE -u $CF_USERNAME -p $CF_PASSWORD_STAGING
            cp config/stag_manifest.yml site/manifest.yml
            cd site
            cf zero-downtime-push original-ausgov -f manifest.yml
  deploy-prod:
    docker:
      - image: govau/cf-cli
    steps:
      - checkout
      - run:
          name: Deploying to cloud.gov.au
          command: |
            cf login -a $CF_API_PROD -o $CF_ORG -s $CF_SPACE -u $CF_USERNAME -p $CF_PASSWORD_PROD
            cp config/prod_manifest.yml site/manifest.yml
            cd site
            cf zero-downtime-push original-ausgov -f manifest.yml
workflows:
  version: 2
  deploy:
    jobs:
      - deploy-covid:
          filters:
            branches:
              only:
                - covid-update
      - deploy-staging:
          filters:
            branches:
              only:
                - develop
                - /infoupdate\/.*/
      - deploy-prod:
          filters:
            branches:
              only:
                - master
